
SELECT PRODUTO
  FROM 
  ( SELECT 'SJSV0015' PRODUTO 
    UNION 
    SELECT 'SJSV0036' PRODUTO 
    UNION 
    SELECT 'SJSV0037' PRODUTO 
    UNION 
    SELECT 'SJSV0038' PRODUTO 
    UNION 
    SELECT 'SJSV0039' PRODUTO 
    UNION 
    SELECT 'SJSV0040' PRODUTO 
    UNION 
    SELECT 'SJSV0041' PRODUTO 
    UNION 
    SELECT 'SJSV0042' PRODUTO 
    UNION 
    SELECT 'SJSV0043' PRODUTO 
    UNION 
    SELECT 'SJSV0044' PRODUTO 
    UNION 
    SELECT 'SJSV0045' PRODUTO 
    UNION 
    SELECT 'SJSV0049' PRODUTO 
    UNION 
    SELECT 'SJSV0050' PRODUTO 
    UNION 
    SELECT 'SJSV0051' PRODUTO 
    UNION 
    SELECT 'SJSV0052' PRODUTO 
  ) PRODS
ORDER BY PRODUTO



