#ifdef SPANISH
    #define STR0001 "Integracion con OpenOffice Writer"
    #define STR0002 "Impresion de Documentos Writer."
    #define STR0003 "Se imprimiran de acuerdo con la Seleccion de parametros."
    #define STR0004 "Impr. &Variaveis"
    #define STR0005 "Impr. &Documento"
    #define STR0006 "(*.DOT)|*.DOT|(*.DOC)|*.DOC|(*.ODT)|*.ODT|(*.OTT)|*.OTT"
    #define STR0007 "Seleccione el archivo"
    #define STR0008 "[DOT][DOC][ODT][OTT]"
    #define STR0009 "Archivo seleccionado"
    #define STR0010 "OK"
    #define STR0011 "Archivo invalido "
    #define STR0012 "Anulada la Seleccion! Usted anulo la seleccion del archivo!"
    #define STR0013 "Sucursal"
    #define STR0014 "Matricula"
    #define STR0015 "Centro de Costo"
    #define STR0016 "Descripcion del Centro de Costo"
    #define STR0017 "Nombre del Empleado"
    #define STR0018 "Nro. CIC/CPF"
    #define STR0019 "Nro. PIS"
    #define STR0020 "Nro. RG"
    #define STR0021 "Nro. CTPS"
    #define STR0022 "Nro. Serie de CTPS"
    #define STR0023 "Prov. Emisora de CTPS"
    #define STR0024 "Nro. Licencia de Conducir"
    #define STR0025 "Nro. Libreta de Serv. Militar"
    #define STR0026 "Nro. Libreta Electoral"
    #define STR0027 "Nro. Zona/Seccion de Libreta Electoral"
    #define STR0028 "Direccion"
    #define STR0029 "Complemento de Direccion"
    #define STR0030 "Barrio"
    #define STR0031 "Municipio"
    #define STR0032 "Sigla de Provincia"
    #define STR0033 "Descripcion de Provincia"
    #define STR0034 "Codigo Postal"
    #define STR0035 "Nro. de Telefono"
    #define STR0036 "Nombre del Padre"
    #define STR0037 "Nombre de la Madre"
    #define STR0038 "Sexo"
    #define STR0039 "Descripcion de Sexo"
    #define STR0040 "Estado Civil"
    #define STR0041 "Codigo de Naturalidad"
    #define STR0042 "Descripcion de Naturalidad"
    #define STR0043 "Codigo de Nacionalidad"
    #define STR0044 "Descripcion de Nacionalidad"
    #define STR0045 "Ano de Llegada al Pais"
    #define STR0046 "Ctd. de Dependientes de IR"
    #define STR0047 "Ctd. de Dependientes de Asign. Familiar"
    #define STR0048 "Fecha de Nacimiento"
    #define STR0049 "Fecha de Ingreso"
    #define STR0050 "Dia de Fecha de Ingreso"
    #define STR0051 "Mes de Fecha de Ingreso"
    #define STR0052 "Ano de Fecha de Ingreso"
    #define STR0053 "Fecha Opcion de FGTS"
    #define STR0054 "Fecha de Despido"
    #define STR0055 "Fecha de Prueba"
    #define STR0056 "Dia de Fecha de Prueba"
    #define STR0057 "Mes de Fecha de Prueba"
    #define STR0058 "Ano de Fecha de Prueba"
    #define STR0059 "Dias de Prueba"
    #define STR0060 "Fecha Vencimiento Examen Medico"
    #define STR0061 "Banco/Agencia Deposito de Sueldo"
    #define STR0062 "Descripcion de Banco de Deposito de Sueldo"
    #define STR0063 "Descripcion de Agencia de Deposito de Sueldo"
    #define STR0064 "Nro. Cuenta de Deposito de Sueldo"
    #define STR0065 "Banco/Agencia de Deposito de FGTS"
    #define STR0066 "Descripcion de Banco de Deposito de FGTS"
    #define STR0067 "Descripcion de Agencia de Deposito de FGTS"
    #define STR0068 "Nro. Cuenta de Deposito de FGTS"
    #define STR0069 "Situacion del Empleado"
    #define STR0070 "Descripcion de Sit. del Empleado"
    #define STR0071 "Horas Mensuales"
    #define STR0072 "Horas Semanales"
    #define STR0073 "Nro. Contratacion"
    #define STR0074 "Codigo de Turno de Trabajo"
    #define STR0075 "Descripcion de Turno de Trabajo"
    #define STR0076 "Codigo de Funcion"
    #define STR0077 "Descripcion de Funcion"
    #define STR0078 "Nro. de CBO"
    #define STR0079 "Codigo Pago Aporte Sindical"
    #define STR0080 "Codigo del Sindicato"
    #define STR0081 "Descripcion del Sindicato"
    #define STR0082 "Codigo Asistencia Medica"
    #define STR0083 "Ctd. de Dependientes para Asistencia Medica"
    #define STR0084 "Cod. del Aumento por Tiempo de Servicio"
    #define STR0085 "Cod. de Canasta Basica"
    #define STR0086 "Cod. Ticket Restaurante"
    #define STR0087 "Cod. de Seguro de Vida"
    #define STR0088 "Porcentaje de Pension Alimenticia"
    #define STR0089 "Porcentaje de Anticipo"
    #define STR0090 "Categoria de Empleado"
    #define STR0091 "Descrip. de Categoria del Empleado"
    #define STR0092 "Descrip. de Tipo de Pago (Mes/Hora)"
    #define STR0093 "Tipo de Pago"
    #define STR0094 "Descrip. de Tipo de Pago"
    #define STR0095 "Sueldo"
    #define STR0096 "Convenio Colectivo"
    #define STR0097 "Base INSS Otras Empresas"
    #define STR0098 "Inss Otras Empresas"
    #define STR0099 "Horas de Peligrosidad"
    #define STR0100 "Horas de Insalubridad Minima"
    #define STR0101 "Horas de Insalubridad Mediana"
    #define STR0102 "Horas de Insalubridad Maxima"
    #define STR0103 "Tipo de Ingreso"
    #define STR0104 "Descrip. de Tipo de Ingreso"
    #define STR0105 "Cod. de Licencia de Antiguedad Lab."
    #define STR0106 "Descripc.de Licencia de Antiguedad"
    #define STR0107 "Codigo de Vinculo Laboral de RAIS"
    #define STR0108 "Descripc. de Vinculo Laboral de RAIS"
    #define STR0109 "Codigo de Instruccion de RAIS"
    #define STR0110 "Descrip. de Codigo de Instruccion de RAIS"
    #define STR0111 "Cod. de Liq. Final de RAIS"
    #define STR0112 "Nro. Credencial"
    #define STR0113 "Codigo de Regla de Apunte"
    #define STR0114 "Foto del Empleado"
    #define STR0115 "Nro. Registro"
    #define STR0116 "Nro. Ficha"
    #define STR0117 "Codigo de Tipo de Contrato de Trabajo"
    #define STR0118 "Descrip. de Tipo de Contrato de Trabajo"
    #define STR0119 "Apodo del Empleado"
    #define STR0120 "E-mail del Empleado"
    #define STR0121 "Texto 01 para libre digitacion"
    #define STR0122 "Texto 02 para libre digitacion"
    #define STR0123 "Texto 03 para libre digitacion"
    #define STR0124 "Texto 04 para libre digitacion"
    #define STR0125 "Sueldo por escrito"
    #define STR0126 "Fecha Base del Sistema"
    #define STR0127 "Dia de Fecha Base del Sistema"
    #define STR0128 "Mes de Fecha Base del Sistema"
    #define STR0129 "Ano de Fecha Base del Sistema"
    #define STR0130 "Nombre de Empresa"
    #define STR0131 "Direccion de Empresa"
    #define STR0132 "Municipio de Empresa"
    #define STR0133 "CP de la Empresa"
    #define STR0134 "CGC de Empresa"
    #define STR0135 "Numero de Inscripc. Provincial de Empresa"
    #define STR0136 "Telefono de Empresa/Fax"
    #define STR0137 "Barrio de Empresa"
    #define STR0138 "Descrip. de Tipo de Liq. Final de RAIS"
    #define STR0139 "Dia de fecha de Despido"
    #define STR0140 "Mes de fecha de Despido"
    #define STR0141 "Ano de fecha de Despido"
    #define STR0142 "Variable"
    #define STR0143 "Descrip. de variable"
    #define STR0144 "Informe Variables GPE_Writer."
    #define STR0145 "Se imprimira de acuerdo con los parametros solicitados "
    #define STR0146 "por el usuario."
    #define STR0147 "A rayas"
    #define STR0148 "Administracion"
    #define STR0149 "Variables                      Descripcion"
    #define STR0150 "Nombre de Dependiente"
    #define STR0151 "Fecha de Nacimiento del Dependiente de Salario Familiar"
    #define STR0152 "Organismo Emisor Doc. Identidad"
    #define STR0153 "Relacion de Dependencia "
    #define STR0154 "Dependiente de Impuesto a la Renta "
    #define STR0155 "Mes de ingreso por escrito "
    #define STR0156 "Nombre del apoderado "
    #define STR0157 "Actividad de la empresa "
    #define STR0158 "Numero del Libro donde se hizo el Registro"
    #define STR0159 "Numero de la Hoja del libro donde fue Registrado"
    #define STR0160 "Fecha de Entrega de los Documentos"
    #define STR0161 "Fecha de la Baja de los Documentos"
    #define STR0162 "Seleccionando Registros....."
    #define STR0163 "Fecha de Nacimiento del Dependiente de Impuesto a la Renta"
    #define STR0164 "Local de Nacimiento"
    #define STR0165 "Numero del Registro de Nacimiento"
    #define STR0166 "Municipio de Nacimiento"
    #define STR0167 "Integracion OpenOffice Writer funciona unicamente con Windows"
    #define STR0168 "Atencion!"
    #define STR0169 "Primer Nombre"
    #define STR0170 "Segundo Nombre"
    #define STR0171 "Primer Apellido"
    #define STR0172 "Segundo Apellido"
    #define STR0173 "Codigo del Proceso"
    #define STR0174 "Codigo del Local de Pago"
    #define STR0175 "Tipo de Salario IMSS"
    #define STR0176 "Tipo de Empleado IMSS"
    #define STR0177 "Tipo de Jornada IMSS"
    #define STR0178 "Fecha de Reingreso"
    #define STR0179 "Fecha de Baja IMSS"
    #define STR0180 "Codigo do Registro Patronal"
    #define STR0181 "Codigo del Departamento"
    #define STR0182 "Codigo de Puesto"
    #define STR0183 "CURP"
    #define STR0184 "Tipo de Infonavit"
    #define STR0185 "Valor de Infonavit"
    #define STR0186 "Nro. de Credito Infonavit"
    #define STR0187 "La direccion completa del lugar donde esta el archivo Writer sobrepaso el limite de 75 caracteres!"
    #define STR0188 "Dia Inicio Per.Adquis.Vacaciones"
    #define STR0189 "Mes Inicio Per.Adquis.Vacaciones"
    #define STR0190 "Ano Inicio Per.Adquis.Vacaciones"
    #define STR0191 "Dia Final Per.Adquis.Vacaciones"
    #define STR0192 "Mes Final Per.Adquis.Vacaciones"
    #define STR0193 "Ano Final Per.Adquis.Vacaciones"
    #define STR0194 "Descripcion del Estado Civil"
    #define STR0195 "Nr. Tarjeta Identidad"
    #define STR0196 "Fecha de Emision de la Tarjeta Identidad"
    #define STR0197 "Descripcion de la primera tarea encontrada"
    #define STR0198 "Clases por semana de la primera tarea"
    #define STR0199 "Cantidad de la primera tarea"
    #define STR0200 "Valor unitario de la primera tarea"
    #define STR0201 "Valor total de la primera tarea"
    #define STR0202 "Descripcion de la segunda tarea"
    #define STR0203 "Clases por semana de la segunda tarea"
    #define STR0204 "Cantidad de la segunda tarea"
    #define STR0205 "Valor unitario de la segunda tarea"
    #define STR0206 "Valor total de la segunda tarea"
    #define STR0207 "Numero Patronal para el CCSS"
    #define STR0208 "Numero de Poliza para MTSS"
    #define STR0209 "Numero de la Sucursal del CCSS"
    #define STR0210 "Codigo de Ocupacion MTSS"
    #define STR0211 "Codigo de Ocupacion CCSS"
    #define STR0212 "Codigo de Ocupacion INS"
    #define STR0213 "Descripcion del codigo de ocupacion MTSS"
    #define STR0214 "Descripcion del codigo de ocupacion CCSS"
    #define STR0215 "Descripcion del codigo de ocupacion INS"
    #define STR0216 "Descripcion del Lugar de Pago"
    #define STR0217 "Turno de Trabajo"
    #define STR0218 "Horas por Dia"
    #define STR0219 "Distrito en que vive el trabajador"
    #define STR0220 "Descripcion del Distrito"
    #define STR0221 "Canton en que vive el trabajador"
    #define STR0222 "Descripcion del canton en que vive el trabajador"
    #define STR0223 "Est/Prov/Reg. en que vive el trabajador"
    #define STR0225 "Tipo de despido de acuerdo con la empresa"
    #define STR0226 "Tipo numero de identificacion"
    #define STR0227 "Numero de Seguridad Social"
    #define STR0228 "Descripcion Jornada"
    #define STR0229 "Fecha de modificacion de sueldo"
    #define STR0230 "Extranjero viviendo en el pais (1=Si, 2=No)"
    #define STR0231 "Tipo de moneda para el sueldo en contrato"
    #define STR0232 "Asociacion Solidarista"
    #define STR0233 "Descripcion Asociacion Solidarista"
    #define STR0234 "Clase Seguro"
    #define STR0235 "Numero Asegurado"
    #define STR0236 "Tipo de gross up de sueldo"
    #define STR0237 "Sueldo Anterior"
    #define STR0238 "Atencion"
    #define STR0239 "Ejecute la opcion del compatibilizador referente al 'Puesto a disposicion los campos RA_HABILIT y RA_COMPLEM para Ecuador'. Para mas informacion, verifique el respectivo Boletin tecnico."
    #define STR0240 "OK"
    #define STR0241 "UF del organismo emisor del doc.identidade"
    #define STR0242 "Exportar Variaveis"
    #define STR0243 "Emissao CTPS"
    #define STR0244 "Raca\Cor"
    #define STR0245 "Data da Segunda Experiencia"
    #define STR0246 "Dia da Segunda Experiencia"
    #define STR0247 "Mes da Segunda Experiencia"
    #define STR0248 "Ano da Segunda Experiencia"
    #define STR0249 "Dias da Segunda Experiencia"
    #define STR0250 "Marca 'x' se Nacionalidade Brasileira"
    #define STR0251 "Marca 'x' se Nacionalidade Extrangeira"
    #define STR0252 "Marca 'x' se Nacionalidade Brasileira Naturalizada"
    #define STR0253 "Marca 'x' se Nacionalidade Brasileiro Nascido no Exterior"
    #define STR0254 "Estado civil de acordo com o NIS/PIS"
    #define STR0255 "Nome do Pai,informa IGNORADO caso esteja em branco"
    #define STR0256 "Nome da Mae,informa IGNORADO caso esteja em branco"
    #define STR0257 "Complemento do RG"
    #define STR0258 "Tipo de Certidao Civil"
    #define STR0259 "Data de Emissao da Certidao Civil"
    #define STR0260 "Termo/Matricula da Certidao Civil"
    #define STR0261 "Livro da Certidao Civil"
    #define STR0262 "Folha da Certidao Civil"
    #define STR0263 "Cartorio da Certidao Civil"
    #define STR0264 "UF da Certidao Civil"
    #define STR0265 "Municipio da Certidao Civil"
    #define STR0266 "Numero do Passaporte"
    #define STR0267 "Orgao Emissor do Passaporte"
    #define STR0268 "UF do Passaporte"
    #define STR0269 "Data Emissao Passaporte"
    #define STR0270 "Data Validade Passaporte"
    #define STR0271 "Pais de Emissao Passaporte"
    #define STR0272 "Numero de Naturalizacao"
    #define STR0273 "Data de Naturalizacao"
    #define STR0274 "Numero do RIC"
    #define STR0275 "Orgao Emissor do RIC"
    #define STR0276 "UF do RIC"
    #define STR0277 "Municipio do RIC"
    #define STR0278 "Data de Expedicao do RIC"
    #define STR0279 "Marca 'x' se Endereco for Comercial"
    #define STR0280 "Marca 'x' se Endereco for Residencial"
    #define STR0281 "Numero do Endereco"
    #define STR0282 "Caixa Postal"
    #define STR0283 "CEP da Caixa Postal"
    #define STR0284 "DDD do Telefone"
    #define STR0285 "DDD do Celular"
    #define STR0286 "Numero do Celular"
    #define STR0287 "Marca 'x' se Empresa por CNPJ"
    #define STR0288 "Marca 'x' se Empresa por CEI"
    #define STR0289 "Data de Expedicao do RIC"
    #define STR0290 "Secao Eleitoral"
    #define STR0291 "Grau de Instrucao conforme NIS/PIS"
    #define STR0292 "Pais de Origem para o DCN/DMN"
    #define STR0295 "Descricao do Grau de Instrucao"
    #define STR0296 "Descricao do Grau de Instrucao"
    #define STR0297 "Descricao do Grau de Instrucao"
    #define STR0298 "Descricao do Grau de Instrucao"
    #define STR0299 "Descricao do Grau de Instrucao"
    #define STR0300 "Descricao do Grau de Instrucao"
    #define STR0301 "Descricao do Grau de Instrucao"
    #define STR0302 "Descricao do Grau de Instrucao"
    #define STR0303 "Descricao do Grau de Instrucao"
    #define STR0304 "Descricao do Grau de Instrucao"
    #define STR0305 "Descricao do Grau de Instrucao"
    #define STR0306 "Descricao do Grau de Instrucao"
    #define STR0307 "Descricao do Grau de Instrucao"
    #define STR0308 "Estado de Nascimento NIS/PIS"
    #define STR0309 "Municipio de Nascimento NIS/PIS"
    #define STR0310 "Marca 'x' para tipo de DMN - Alteracao"
    #define STR0311 "Marca 'x' para tipo de DMN - Cadastro Retroativo"
    #define STR0312 "Marca 'x' para tipo de DMN - Cancelamento"
    #define STR0313 "Marca 'x' para tipo de DMN - Reativacao"
    #define STR0314 "Marca 'x' para tipo de DMN - Retroacao Cadastral"
    #define STR0315 "Marca 'x' se sexo for Masculino"
    #define STR0316 "Marca 'x' se sexo for Feminino"
    #define STR0317 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0318 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0319 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0320 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0321 "Informe o Tipo de Alteracao do NIS-PIS"
    #define STR0322 "Nenhum"
    #define STR0323 "Alteracao"
    #define STR0324 "Cadastro Retroativo"
    #define STR0325 "Cancelamento"
    #define STR0326 "Reativacao"
    #define STR0327 "Retroacao Cadastral"
    #define STR0328 "Endereco da Localidade de Pagamento"
    #define STR0329 "Bairro da Localidade de Pagamento"
    #define STR0330 "Cidade da Localidade de Pagamento"
    #define STR0331 "Estado da Localidade de Pagamento"
    #define STR0332 "Municipio da Localidade de Pagamento"
    #define STR0333 "CEP da Localidade de Pagamento"
    #define STR0334 "Requisitos da Funcao"
    #define STR0335 "Idade"    
    #define STR0336 "Codigo da Serventia"
    #define STR0337 "Codigo do Acervo"
    #define STR0338 "Registro Civil"
    #define STR0339 "Tipo do Livro Reg."
    #define STR0340 ""
    #define STR0341 ""
    #define STR0342 ""
    #define STR0343 ""
    #define STR0344 ""
    #define STR0345 ""
    #define STR0346 ""
    #define STR0347 ""
    #define STR0348 ""
    #define STR0349 ""
    #define STR0350 ""
    #define STR0351 ""
    #define STR0352 ""
    #define STR0353 ""
    #define STR0354 ""
    #define STR0355 ""
    #define STR0356 ""
    #define STR0357 ""
    #define STR0358 ""
    #define STR0359 ""
    #define STR0360 ""
    #define STR0361 ""
    #define STR0362 ""
    #define STR0363 ""
    #define STR0364 ""
    #define STR0365 ""
    #define STR0366 ""
    #define STR0367 ""
    #define STR0368 ""
    #define STR0369 ""
    #define STR0370 ""
    #define STR0371 ""
    #define STR0372 ""
    #define STR0373 ""
    #define STR0374 ""
    #define STR0375 ""
    #define STR0376 ""
    #define STR0377 ""
    #define STR0378 ""
    #define STR0379 ""
    #define STR0380 ""
    #define STR0381 ""
    #define STR0382 ""
    #define STR0383 ""
    #define STR0384 ""
    #define STR0385 ""
    #define STR0386 ""
    #define STR0387 ""
    #define STR0388 ""
    #define STR0389 ""
    #define STR0390 "Descricao da atividade da funcao"
#else
    #ifdef ENGLISH
        #define STR0001 "Integration with OpenOffice Writer"
        #define STR0002 "Print of Writer Documents."
        #define STR0003 " They will be printed according to the Parameters Selection."
        #define STR0004 "Print&Variables"
        #define STR0005 "Print&Document"
        #define STR0006 "(*.DOT)|*.DOT|(*.DOC)|*.DOC|(*.ODT)|*.ODT|(*.OTT)|*.OTT"
        #define STR0007 "Select the file    "
        #define STR0008 "[DOT][DOC][ODT][OTT]"
        #define STR0009 "Selected File"
        #define STR0010 "OK"
        #define STR0011 "Invalid File"
        #define STR0012 "Selection canceled! You canceled file selection."
        #define STR0013 "Branch"
        #define STR0014 "Registrat."
        #define STR0015 "Cost Center"
        #define STR0016 "Cost Center Description"
        #define STR0017 "Employee's Name"
        #define STR0018 "CIC/CPF Number"
        #define STR0019 "PIS Number"
        #define STR0020 "ID Number"
        #define STR0021 "CTPS Number"
        #define STR0022 "CTPS Serial Number"
        #define STR0023 "State that issued the CTPS"
        #define STR0024 "Driving License Number (CNH)"
        #define STR0025 "Reservist Card Number"
        #define STR0026 "Voting Card Number"
        #define STR0027 "Voting Card Zone/Section Number"
        #define STR0028 "Address"
        #define STR0029 "Address complement"
        #define STR0030 "District"
        #define STR0031 "City"
        #define STR0032 "State acronym  "
        #define STR0033 "State description  "
        #define STR0034 "ZIP code number"
        #define STR0035 "Telephone number"
        #define STR0036 "Father's name"
        #define STR0037 "Mother's name"
        #define STR0038 "Sex"
        #define STR0039 "Sex Description"
        #define STR0040 "Marital Status"
        #define STR0041 "Birth Place Code"
        #define STR0042 "Birth Place Description"
        #define STR0043 "Nationality Code"
        #define STR0044 "Nationality Description"
        #define STR0045 "Year of Arrival in the Country"
        #define STR0046 "Number of Income Tax Dependants"
        #define STR0047 "Number of Family Salary Dependants"
        #define STR0048 "Birth date"
        #define STR0049 "Admission Date"
        #define STR0050 "Admission Day"
        #define STR0051 "Admission Month"
        #define STR0052 "Admission Year"
        #define STR0053 "FGTS Option Date"
        #define STR0054 "Dismissal Date"
        #define STR0055 "Trial Period Date"
        #define STR0056 "Trial Period Day"
        #define STR0057 "Trial Period Month"
        #define STR0058 "Trial Period Year"
        #define STR0059 "Trial Period Days"
        #define STR0060 "Medical Examination Due Date"
        #define STR0061 "Bank/Branch for Salary Deposit"
        #define STR0062 "Description of the Bank for Salary Deposit"
        #define STR0063 "Description of the Agency for Salary Deposit"
        #define STR0064 "Account Number for Salary Deposit"
        #define STR0065 "Bank/Branch for FGTS Deposit"
        #define STR0066 "Description of the Bank for FGTS Deposit"
        #define STR0067 "Description of the Branch for FGTS Deposit"
        #define STR0068 "Account Number for FGTS Deposit"
        #define STR0069 "Payroll Status"
        #define STR0070 "Description of the Payroll Status"
        #define STR0071 "Monthly Hours"
        #define STR0072 "Weekly Hours"
        #define STR0073 "Registration Number"
        #define STR0074 "Code of the Work Shift"
        #define STR0075 "Description of the Work Shift"
        #define STR0076 "Role code       "
        #define STR0077 "Role Description   "
        #define STR0078 "CBO Number"
        #define STR0079 "Code for Payment of Union Dues"
        #define STR0080 "Labor Union Code"
        #define STR0081 "Labor Union Description"
        #define STR0082 "Health Insurance Code"
        #define STR0083 "Number of Dependants for Health Insurance"
        #define STR0084 "Code of Differential for Service Period"
        #define STR0085 "Basic Basket Code"
        #define STR0086 "Meal Ticket Code"
        #define STR0087 "Life Insurance Code"
        #define STR0088 "Percentage of Alimony"
        #define STR0089 "Percentage of Advance"
        #define STR0090 "Employee's Category"
        #define STR0091 "Description of the Employee's Category"
        #define STR0092 "Description of the Payment Type (Month/Hour)"
        #define STR0093 "Payment Type"
        #define STR0094 "Description of Payment Type"
        #define STR0095 "Salary"
        #define STR0096 "Labor Agreement"
        #define STR0097 "INSS Base Other Companies"
        #define STR0098 "INSS Other Companies"
        #define STR0099 "Hours of Risk"
        #define STR0100 "Hours of Minimum Insalubrity"
        #define STR0101 "Hours of Medium Insalubrity"
        #define STR0102 "Hours of Maximum Insalubrity"
        #define STR0103 "Admission Type"
        #define STR0104 "Description of Admission Type"
        #define STR0105 "FGTS Absence Code"
        #define STR0106 "Description of FGTS Absence"
        #define STR0107 "Code of RAIS Employment Relationship"
        #define STR0108 "Description of RIAS Employment Relationship"
        #define STR0109 "RAIS Instruction Code"
        #define STR0110 "Description of RAIS Instruction Code"
        #define STR0111 "RAIS Termination Code"
        #define STR0112 "Badge Number"
        #define STR0113 "Code of Annotation Rule"
        #define STR0114 "Employee's Picture"
        #define STR0115 "Registration Number"
        #define STR0116 "File Card Number"
        #define STR0117 "Code of Work Contract Type"
        #define STR0118 "Description of Work Contract Type"
        #define STR0119 "Employee's Nickname"
        #define STR0120 "Employee's E-mail"
        #define STR0121 "Text 01 for Free Typing"
        #define STR0122 "Text 02 for Free Typing"
        #define STR0123 "Text 03 for Free Typing"
        #define STR0124 "Text 04 for Free Typing"
        #define STR0125 "Salary written in full"
        #define STR0126 "System Base Date"
        #define STR0127 "System Base Date Day"
        #define STR0128 "System Base Date Month"
        #define STR0129 "System Base Date Year"
        #define STR0130 "Company Name"
        #define STR0131 "Company Address"
        #define STR0132 "Company City"
        #define STR0133 "Company Zip Code"
        #define STR0134 "Company CGC"
        #define STR0135 "Company State Registration Number"
        #define STR0136 "Company Telephone/Fax"
        #define STR0137 "Company District"
        #define STR0138 "Description of RAIS Termination Type"
        #define STR0139 "Dismissal Day"
        #define STR0140 "Dismissal Month"
        #define STR0141 "Dismissal Year"
        #define STR0142 "Variable"
        #define STR0143 "Variable Description"
        #define STR0144 "GPE_Writer Variables Report."
        #define STR0145 "It will be printed according to the parameters required by"
        #define STR0146 "the user."
        #define STR0147 "Z. Form"
        #define STR0148 "Management"
        #define STR0149 "Variables                      Descript."
        #define STR0150 "Dependant's name"
        #define STR0151 "Dependant's Birth Date"
        #define STR0152 "Agency that has Issued the ID"
        #define STR0153 "Dependence Relationship"
        #define STR0154 "Income Tax Dependant"
        #define STR0155 "Admittance Month written in full"
        #define STR0156 "Attorney-at-fact's name"
        #define STR0157 "Company Activity"
        #define STR0158 "Book Number where registered"
        #define STR0159 "Book Sheet Number where Registered"
        #define STR0160 "Document delivery date"
        #define STR0161 "Document posting date"
        #define STR0162 "Selecting Files....."
        #define STR0163 "Date of Dependent's Birth acc. Income Tax"
        #define STR0164 "Place of Birth"
        #define STR0165 "Number of Birth Certificate"
        #define STR0166 "City of Birth"
        #define STR0167 "OpenOffice Writer integration works only with Windows."
        #define STR0168 "Attention!"
        #define STR0169 "First Name"
        #define STR0170 "Second Name"
        #define STR0171 "First Family Name"
        #define STR0172 "Second Family Name"
        #define STR0173 "Process Code"
        #define STR0174 "Code of Payment Place"
        #define STR0175 "IMSS Salary Type"
        #define STR0176 "IMSS Employee Type"
        #define STR0177 "IMSS Work Shift Type"
        #define STR0178 "Readmission Date"
        #define STR0179 "IMSS Posting Date"
        #define STR0180 "Patronal Registration Code"
        #define STR0181 "Department Code"
        #define STR0182 "Station Code"
        #define STR0183 "CURP"
        #define STR0184 "Infonavit Type"
        #define STR0185 "Infonavit Value"
        #define STR0186 "Infonavit Credit Number"
        #define STR0187 "Complete address of the place where Writer file is exceeded the limit of 75 characters!"
        #define STR0188 "Day Begin. VacationAquis.Per."
        #define STR0189 "Month Begin. VacationAquis.Per."
        #define STR0190 "Year Begin. VacationAquis.Per."
        #define STR0191 "Day End VacationAquis.Per."
        #define STR0192 "Month End VacationAquis.Per."
        #define STR0193 "Year End VacationAquis.Per."
        #define STR0194 "Marital status description"
        #define STR0195 "No. Identity card"
        #define STR0196 "Issue date of identity card"
        #define STR0197 "Description of the first task found"
        #define STR0198 "Classes per week of the first task"
        #define STR0199 "Amount of the first task"
        #define STR0200 "Unit value of the first task"
        #define STR0201 "Total value of the first task"
        #define STR0202 "Description of the second task"
        #define STR0203 "Classes per week of the second task"
        #define STR0204 "Amount of the second task"
        #define STR0205 "Unit value of the second task"
        #define STR0206 "Total value of the second task"
        #define STR0207 "Numero Patronal para o CCSS"
        #define STR0208 "Numero de Apolice para MTSS"
        #define STR0209 "Numero da Filial do CCSS"
        #define STR0210 "Codigo de Ocupacao MTSS"
        #define STR0211 "Codigo de Ocupacao CCSS"
        #define STR0212 "Codigo de Ocupacao INS"
        #define STR0213 "Descricao do Codigo de Ocupacao MTSS"
        #define STR0214 "Descricao do Codigo de Ocupacao CCSS"
        #define STR0215 "Descricao do Codigo de Ocupacao INS"
        #define STR0216 "Descricao da Localidade de Pagamento"
        #define STR0217 "Turno de Trabalho"
        #define STR0218 "Horas por Dia"
        #define STR0219 "Distrito onde vive o trabalhador"
        #define STR0220 "Descricao do Distrito"
        #define STR0221 "Cantao onde vive o trabalhador"
        #define STR0222 "Descricao do Cantao onde vive o trabalhador"
        #define STR0223 "Estado onde vive o trabalhador"
        #define STR0225 "Tipo de Demissao de Acordo com a Empresa"
        #define STR0226 "Tipo numero de identificacao"
        #define STR0227 "Numero do Seguro Social"
        #define STR0228 "Descricao Jornada"
        #define STR0229 "Data de Modificacao de Salario"
        #define STR0230 "Estrangeiro vivendo no pais (1=Sim, 2=Nao)"
        #define STR0231 "Tipo de Moeda para o Salario em contrato"
        #define STR0232 "Associacao Solidarista"
        #define STR0233 "Descricao Associacao Solidarista"
        #define STR0234 "Classe Seguro"
        #define STR0235 "Numero Assegurado"
        #define STR0236 "Tipo de Gross up de Salario"
        #define STR0237 "Salario Anterior"
        #define STR0238 "Attention"
        #define STR0239 "Run the compatibility option related to 'Availability of the fields RA_HABILIT and RA_COMPLEM for Ecuador'. For more information, check the respective Technical Newsletter."
        #define STR0240 "OK"
        #define STR0241 "UF do Orgao Emissor Do Doc.identidade"
        #define STR0242 "Exportar Variaveis"
    #define STR0243 "Emissao CTPS"
    #define STR0244 "Raca\Cor"
    #define STR0245 "Data da Segunda Experiencia"
    #define STR0246 "Dia da Segunda Experiencia"
    #define STR0247 "Mes da Segunda Experiencia"
    #define STR0248 "Ano da Segunda Experiencia"
    #define STR0249 "Dias da Segunda Experiencia"
    #define STR0250 "Marca 'x' se Nacionalidade Brasileira"
    #define STR0251 "Marca 'x' se Nacionalidade Extrangeira"
    #define STR0252 "Marca 'x' se Nacionalidade Brasileira Naturalizada"
    #define STR0253 "Marca 'x' se Nacionalidade Brasileiro Nascido no Exterior"
    #define STR0254 "Estado civil de acordo com o NIS/PIS"
    #define STR0255 "Nome do Pai,informa IGNORADO caso esteja em branco"
    #define STR0256 "Nome da Mae,informa IGNORADO caso esteja em branco"
    #define STR0257 "Complemento do RG"
    #define STR0258 "Tipo de Certidao Civil"
    #define STR0259 "Data de Emissao da Certidao Civil"
    #define STR0260 "Termo/Matricula da Certidao Civil"
    #define STR0261 "Livro da Certidao Civil"
    #define STR0262 "Folha da Certidao Civil"
    #define STR0263 "Cartorio da Certidao Civil"
    #define STR0264 "UF da Certidao Civil"
    #define STR0265 "Municipio da Certidao Civil"
    #define STR0266 "Numero do Passaporte"
    #define STR0267 "Orgao Emissor do Passaporte"
    #define STR0268 "UF do Passaporte"
    #define STR0269 "Data Emissao Passaporte"
    #define STR0270 "Data Validade Passaporte"
    #define STR0271 "Pais de Emissao Passaporte"
    #define STR0272 "Numero de Naturalizacao"
    #define STR0273 "Data de Naturalizacao"
    #define STR0274 "Numero do RIC"
    #define STR0275 "Orgao Emissor do RIC"
    #define STR0276 "UF do RIC"
    #define STR0277 "Municipio do RIC"
    #define STR0278 "Data de Expedicao do RIC"
    #define STR0279 "Marca 'x' se Endereco for Comercial"
    #define STR0280 "Marca 'x' se Endereco for Residencial"
    #define STR0281 "Numero do Endereco"
    #define STR0282 "Caixa Postal"
    #define STR0283 "CEP da Caixa Postal"
    #define STR0284 "DDD do Telefone"
    #define STR0285 "DDD do Celular"
    #define STR0286 "Numero do Celular"
    #define STR0287 "Marca 'x' se Empresa por CNPJ"
    #define STR0288 "Marca 'x' se Empresa por CEI"
    #define STR0289 "Data de Expedicao do RIC"
    #define STR0290 "Secao Eleitoral"
    #define STR0291 "Grau de Instrucao conforme NIS/PIS"
    #define STR0292 "Pais de Origem para o DCN/DMN"
    #define STR0295 "Descricao do Grau de Instrucao"
    #define STR0296 "Descricao do Grau de Instrucao"
    #define STR0297 "Descricao do Grau de Instrucao"
    #define STR0298 "Descricao do Grau de Instrucao"
    #define STR0299 "Descricao do Grau de Instrucao"
    #define STR0300 "Descricao do Grau de Instrucao"
    #define STR0301 "Descricao do Grau de Instrucao"
    #define STR0302 "Descricao do Grau de Instrucao"
    #define STR0303 "Descricao do Grau de Instrucao"
    #define STR0304 "Descricao do Grau de Instrucao"
    #define STR0305 "Descricao do Grau de Instrucao"
    #define STR0306 "Descricao do Grau de Instrucao"
    #define STR0307 "Descricao do Grau de Instrucao"
    #define STR0308 "Estado de Nascimento NIS/PIS"
    #define STR0309 "Municipio de Nascimento NIS/PIS"
    #define STR0310 "Marca 'x' para tipo de DMN - Alteracao"
    #define STR0311 "Marca 'x' para tipo de DMN - Cadastro Retroativo"
    #define STR0312 "Marca 'x' para tipo de DMN - Cancelamento"
    #define STR0313 "Marca 'x' para tipo de DMN - Reativacao"
    #define STR0314 "Marca 'x' para tipo de DMN - Retroacao Cadastral"
    #define STR0315 "Marca 'x' se sexo for Masculino"
    #define STR0316 "Marca 'x' se sexo for Feminino"
    #define STR0317 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0318 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0319 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0320 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0321 "Informe o Tipo de Alteracao do NIS-PIS"
    #define STR0322 "Nenhum"
    #define STR0323 "Alteracao"
    #define STR0324 "Cadastro Retroativo"
    #define STR0325 "Cancelamento"
    #define STR0326 "Reativacao"
    #define STR0327 "Retroacao Cadastral"
    #define STR0328 "Endereco da Localidade de Pagamento"
    #define STR0329 "Bairro da Localidade de Pagamento"
    #define STR0330 "Cidade da Localidade de Pagamento"
    #define STR0331 "Estado da Localidade de Pagamento"
    #define STR0332 "Municipio da Localidade de Pagamento"
    #define STR0333 "CEP da Localidade de Pagamento"
    #define STR0334 "Requisitos da Funcao"
    #define STR0335 "Idade"    
    #define STR0336 "Codigo da Serventia"
    #define STR0337 "Codigo do Acervo"
    #define STR0338 "Registro Civil"
    #define STR0339 "Tipo do Livro Reg."
    #define STR0340 ""
    #define STR0341 ""
    #define STR0342 ""
    #define STR0343 ""
    #define STR0344 ""
    #define STR0345 ""
    #define STR0346 ""
    #define STR0347 ""
    #define STR0348 ""
    #define STR0349 ""
    #define STR0350 ""
    #define STR0351 ""
    #define STR0352 ""
    #define STR0353 ""
    #define STR0354 ""
    #define STR0355 ""
    #define STR0356 ""
    #define STR0357 ""
    #define STR0358 ""
    #define STR0359 ""
    #define STR0360 ""
    #define STR0361 ""
    #define STR0362 ""
    #define STR0363 ""
    #define STR0364 ""
    #define STR0365 ""
    #define STR0366 ""
    #define STR0367 ""
    #define STR0368 ""
    #define STR0369 ""
    #define STR0370 ""
    #define STR0371 ""
    #define STR0372 ""
    #define STR0373 ""
    #define STR0374 ""
    #define STR0375 ""
    #define STR0376 ""
    #define STR0377 ""
    #define STR0378 ""
    #define STR0379 ""
    #define STR0380 ""
    #define STR0381 ""
    #define STR0382 ""
    #define STR0383 ""
    #define STR0384 ""
    #define STR0385 ""
    #define STR0386 ""
    #define STR0387 ""
    #define STR0388 ""
    #define STR0389 ""
    #define STR0390 "Descricao da atividade da funcao"
    #else
        #define STR0001 If( cPaisLoc $ "ANG|PTG", "Integracao Com OpenOffice Writer", "Integracao com OpenOffice Writer" )
        #define STR0002 If( cPaisLoc $ "ANG|PTG", "Impressao de documentos no Writer.", "Impressao de Documentos OpenOffice Writer." )
        #define STR0003 If( cPaisLoc $ "ANG|PTG", "Serao impressos de acordo com a seleccao Dos Parametros.", "Serao impressos de acordo com a selecao dos parametros." )
        #define STR0004 If( cPaisLoc $ "ANG|PTG", "Impr. &variaveis", "Impr. &Variaveis" )
        #define STR0005 If( cPaisLoc $ "ANG|PTG", "Impr. &documento", "Impr. &Documento" )
        #define STR0006 If( cPaisLoc $ "ANG|PTG", "(*.DOT)|*.DOT|(*.DOC)|*.DOC|(*.ODT)|*.ODT|(*.OTT)|*.OTT", "(*.DOT)|*.DOT|(*.DOC)|*.DOC|(*.ODT)|*.ODT|(*.OTT)|*.OTT" )
        #define STR0007 If( cPaisLoc $ "ANG|PTG", "Seleccionar o ficheiro", "Selecione o arquivo" )
        #define STR0008 If( cPaisLoc $ "ANG|PTG", "[DOT][DOC][ODT][OTT]", "[DOT][DOC][ODT][OTT]" )
        #define STR0009 If( cPaisLoc $ "ANG|PTG", "Ficheiro Seleccionado", "Arquivo Selecionado" )
        #define STR0010 If( cPaisLoc $ "ANG|PTG", "Ok", "OK" )
        #define STR0011 If( cPaisLoc $ "ANG|PTG", "Ficheiro invalido ", "Arquivo Invalido " )
        #define STR0012 If( cPaisLoc $ "ANG|PTG", "Cancelada a Seleccao! Voce cancelou a seleccao do registo.", "Cancelada a selecao! Voce cancelou a selecao do arquivo." )
        #define STR0013 "Filial"
        #define STR0014 If( cPaisLoc $ "ANG|PTG", "Matricula", "Matricula" )
        #define STR0015 If( cPaisLoc $ "ANG|PTG", "Centro De Custo", "Centro de Custo" )
        #define STR0016 If( cPaisLoc $ "ANG|PTG", "Descricao Do Centro De Custo", "Descricao do Centro de Custo" )
        #define STR0017 If( cPaisLoc $ "ANG|PTG", "Nome Do Funcionario", "Nome do Funcionario" )
        #define STR0018 If( cPaisLoc $ "ANG|PTG", "Numero Do Cic/cpf", "Numero do CIC/CPF" )
        #define STR0019 If( cPaisLoc $ "ANG|PTG", "Numero Do Pis", "Numero do PIS" )
        #define STR0020 If( cPaisLoc $ "ANG|PTG", "Numero Do Rg", "Numero do RG" )
        #define STR0021 If( cPaisLoc $ "ANG|PTG", "Numero Da Ctps", "Numero da CTPS" )
        #define STR0022 If( cPaisLoc $ "ANG|PTG", "Numero De Serie Da Ctps", "Numero de Serie da CTPS" )
        #define STR0023 If( cPaisLoc $ "ANG|PTG", "Estado Emissor Da Ctps", "Estado Emissor da CTPS" )
        #define STR0024 If( cPaisLoc $ "ANG|PTG", "Numero Da Carteira Nacional De Habilitacao", "Numero da Carteira Nacional de Habilitacao" )
        #define STR0025 If( cPaisLoc $ "ANG|PTG", "Numero Do Documento De Passagem a Reserva Territorial", "Numero da Carteira de Reservista" )
        #define STR0026 If( cPaisLoc $ "ANG|PTG", "Numero Do Cartao De Eleitor", "Numero do Titulo de Eleitor" )
        #define STR0027 If( cPaisLoc $ "ANG|PTG", "Numero Da Zona/seccao Do Cartao De Eleitor", "Numero da Zona/Secao do Tiluto de Eleitor" )
        #define STR0028 If( cPaisLoc $ "ANG|PTG", "Morada", "Endereco" )
        #define STR0029 If( cPaisLoc $ "ANG|PTG", "Complemento De Morada", "Complemento de Endereco" )
        #define STR0030 If( cPaisLoc $ "ANG|PTG", "Localidade", "Bairro" )
        #define STR0031 If( cPaisLoc $ "ANG|PTG", "Concelho", "Municipio" )
        #define STR0032 If( cPaisLoc $ "ANG|PTG", "Sigla Do Estado", "Sigla do Estado" )
        #define STR0033 If( cPaisLoc $ "ANG|PTG", "Descricao Do Estado", "Descricao do Estado" )
        #define STR0034 If( cPaisLoc $ "ANG|PTG", "Numero Do Cep", "Numero do CEP" )
        #define STR0035 If( cPaisLoc $ "ANG|PTG", "Numero De Telefone", "Numero do Telefone" )
        #define STR0036 If( cPaisLoc $ "ANG|PTG", "Nome Do Pai", "Nome do Pai" )
        #define STR0037 If( cPaisLoc $ "ANG|PTG", "Nome Da Mae", "Nome da Mae" )
        #define STR0038 "Sexo"
        #define STR0039 If( cPaisLoc $ "ANG|PTG", "Descricao Do Sexo", "Descricao do Sexo" )
        #define STR0040 "Estado Civil"
        #define STR0041 If( cPaisLoc $ "ANG|PTG", "Codigo Da Naturalidade", "Codigo da Naturalidade" )
        #define STR0042 If( cPaisLoc $ "ANG|PTG", "Descricao Da Naturalidade", "Descricao da Naturalidade" )
        #define STR0043 If( cPaisLoc $ "ANG|PTG", "Codigo Da Nacionalidade", "Codigo da Nacionalidade" )
        #define STR0044 If( cPaisLoc $ "ANG|PTG", "Descricao Da Nacionalidade", "Descricao da Nacionalidade" )
        #define STR0045 If( cPaisLoc $ "ANG|PTG", "Ano De Chegada Ao Pais", "Ano de Chegada no Pais" )
        #define STR0046 If( cPaisLoc $ "ANG|PTG", "Numero De Dependentes De Ir", "Numero de Dependentes de IR" )
        #define STR0047 If( cPaisLoc $ "ANG|PTG", "Numero De Dependentes Do Rendimento Familiar", "Numero de Dependentes de Salario Familia" )
        #define STR0048 If( cPaisLoc $ "ANG|PTG", "Data De Nascimento", "Data de Nascimento" )
        #define STR0049 If( cPaisLoc $ "ANG|PTG", "Data De Admissao", "Data de Admissao" )
        #define STR0050 If( cPaisLoc $ "ANG|PTG", "Dia Da Data De Admissao", "Dia da Data de Admissao" )
        #define STR0051 If( cPaisLoc $ "ANG|PTG", "Mes Da Data De Admissao", "Mes da Data de Admissao" )
        #define STR0052 If( cPaisLoc $ "ANG|PTG", "Ano Da Data De Admissao", "Ano da Data de Admissao" )
        #define STR0053 If( cPaisLoc $ "ANG|PTG", "Data Da Opcao Do Fgts", "Data da Opcao do FGTS" )
        #define STR0054 If( cPaisLoc $ "ANG|PTG", "Data De Demissao", "Data de Demissao" )
        #define STR0055 If( cPaisLoc $ "ANG|PTG", "Data De Experiencia", "Data de Experiencia" )
        #define STR0056 If( cPaisLoc $ "ANG|PTG", "Dia Da Data De Experiencia", "Dia da Data de Experiencia" )
        #define STR0057 If( cPaisLoc $ "ANG|PTG", "Mes Da Data De Experiencia", "Mes da Data de Experiencia" )
        #define STR0058 If( cPaisLoc $ "ANG|PTG", "Ano Da Data De Experiencia", "Ano da Data de Experiencia" )
        #define STR0059 If( cPaisLoc $ "ANG|PTG", "Dias De Experiencia", "Dias de Experiencia" )
        #define STR0060 If( cPaisLoc $ "ANG|PTG", "Data De Validade Do Exame Medico", "Data Vencimento Exame Medico" )
        #define STR0061 If( cPaisLoc $ "ANG|PTG", "Banco/agencia De Deposito Do Ordenado", "Banco/Agencia Deposito de Salario" )
        #define STR0062 If( cPaisLoc $ "ANG|PTG", "Descricao Do Banco De Deposito Do Ordenado", "Descricao do Banco de Deposito de Salario" )
        #define STR0063 If( cPaisLoc $ "ANG|PTG", "Descricao Da Agencia De Deposito Do Ordenado", "Descricao da Agencia de Deposito de Salario" )
        #define STR0064 If( cPaisLoc $ "ANG|PTG", "Numero Da Conta De Deposito Do Ordenado", "Numero da Conta de Deposito de Salario" )
        #define STR0065 If( cPaisLoc $ "ANG|PTG", "Banco/agencia De Deposito Do Fgts", "Banco/Agencia de Deposito do FGTS" )
        #define STR0066 If( cPaisLoc $ "ANG|PTG", "Descricao Do Banco De Deposito De Fgts", "Descricao da Banco do Deposito de FGTS" )
        #define STR0067 If( cPaisLoc $ "ANG|PTG", "Descricao Da Agencia De Deposito Do Fgts", "Descricao da Agencia de Deposito do FGTS" )
        #define STR0068 If( cPaisLoc $ "ANG|PTG", "Numero Da Conta De Deposito Do Fgts", "Numero da Conta de Deposito do FGTS" )
        #define STR0069 If( cPaisLoc $ "ANG|PTG", "Situacao Na Folha", "Situacao na Folha" )
        #define STR0070 If( cPaisLoc $ "ANG|PTG", "Descricao Da Situacao Na Folha", "Descricao da Situacao na Folha" )
        #define STR0071 "Horas Mensais"
        #define STR0072 "Horas Semanais"
        #define STR0073 If( cPaisLoc $ "ANG|PTG", "Numero Da Folha", "Numero da Chapa" )
        #define STR0074 If( cPaisLoc $ "ANG|PTG", "Codigo Do Turno De Trabalho", "Codigo do Turno de Trabalho" )
        #define STR0075 If( cPaisLoc $ "ANG|PTG", "Descricao Do Turno De Trabalho", "Descricao do Turno de Trabalho" )
        #define STR0076 If( cPaisLoc $ "ANG|PTG", "Codigo Da Funcao", "Codigo da Funcao" )
        #define STR0077 If( cPaisLoc $ "ANG|PTG", "Descricao Da Funcao", "Descricao da Funcao" )
        #define STR0078 If( cPaisLoc $ "ANG|PTG", "Numero Do Cbo", "Numero do CBO" )
        #define STR0079 If( cPaisLoc $ "ANG|PTG", "Codigo De Pagamento Da Contribuicao Sindical", "Codigo Pagamento Contribuicao Sindical" )
        #define STR0080 If( cPaisLoc $ "ANG|PTG", "Codigo Do Sindicato", "Codigo do Sindicato" )
        #define STR0081 If( cPaisLoc $ "ANG|PTG", "Descricao Do Sindicato", "Descricao do Sindicato" )
        #define STR0082 If( cPaisLoc $ "ANG|PTG", "Codigo De Assistencia Medica", "Codigo Assistencia Medica" )
        #define STR0083 If( cPaisLoc $ "ANG|PTG", "Numero De Dependentes Para Assistencia Medica", "Numero de Dependentes para Assistencia Medica" )
        #define STR0084 If( cPaisLoc $ "ANG|PTG", "Codigo Do Valor Adicional Por Tempo De Servico", "Codigo do Adicional Por Tempo de Servico" )
        #define STR0085 If( cPaisLoc $ "ANG|PTG", "Codigo Da Cesta Basica", "Codigo da Cesta Basica" )
        #define STR0086 If( cPaisLoc $ "ANG|PTG", "Codigo Do Vale De Refeicao", "Codigo do Vale Refeicao" )
        #define STR0087 If( cPaisLoc $ "ANG|PTG", "Codigo Do Seguro De Vida", "Codigo do Seguro de Vida" )
        #define STR0088 If( cPaisLoc $ "ANG|PTG", "Percentagem Da Pensao Alimenticia", "Percentual da Pensao Alimenticia" )
        #define STR0089 If( cPaisLoc $ "ANG|PTG", "Percentagem Do Adiantamento", "Percentual do Adiantamento" )
        #define STR0090 If( cPaisLoc $ "ANG|PTG", "Categoria Do Funcionario", "Categoria do Funcionario" )
        #define STR0091 If( cPaisLoc $ "ANG|PTG", "Descricao Da Categoria Do Funcionario", "Descricao da Categoria do Funcionario" )
        #define STR0092 If( cPaisLoc $ "ANG|PTG", "Descricao do tipo de pagamento (mes/hora)", "Descricao do Tipo de Pagamento (Mes/Hora)" )
        #define STR0093 If( cPaisLoc $ "ANG|PTG", "Tipo De Pagamento", "Tipo de Pagamento" )
        #define STR0094 If( cPaisLoc $ "ANG|PTG", "Descricao Do Tipo De Pagamento", "Descricao do Tipo de Pagamento" )
        #define STR0095 If( cPaisLoc $ "ANG|PTG", "Salario", "Salario" )
        #define STR0096 If( cPaisLoc $ "ANG|PTG", "Ordenado Divergente", "Salario Dissidio" )
        #define STR0097 If( cPaisLoc $ "ANG|PTG", "Base Do Ss Outras Empresas", "Base INSS Outras Empresas" )
        #define STR0098 If( cPaisLoc $ "ANG|PTG", "Ss Das Outras Empresas", "Inss Outras Empresas" )
        #define STR0099 If( cPaisLoc $ "ANG|PTG", "Horas De Perigo", "Horas de Periculosidade" )
        #define STR0100 If( cPaisLoc $ "ANG|PTG", "Horas De Insalubridade Minima", "Horas de Insalubridade Minima" )
        #define STR0101 If( cPaisLoc $ "ANG|PTG", "Horas De Insalubridade Media", "Horas de Insalubridade Media" )
        #define STR0102 If( cPaisLoc $ "ANG|PTG", "Horas De Insalubridade Maxima", "Horas de Insalubridade Maxima" )
        #define STR0103 If( cPaisLoc $ "ANG|PTG", "Tipo De Admissao", "Tipo de Admissao" )
        #define STR0104 If( cPaisLoc $ "ANG|PTG", "Descricao Do Tipo De Admissao", "Descricao do Tipo de Admissao" )
        #define STR0105 If( cPaisLoc $ "ANG|PTG", "Codigo De Afastamento Do Fgts", "Codigo de Afastamento do FGTS" )
        #define STR0106 If( cPaisLoc $ "ANG|PTG", "Descricao Do Afastamento Do Fgts", "Descricao do Afastamento do FGTS" )
        #define STR0107 If( cPaisLoc $ "ANG|PTG", "Codigo Do Vinculo De Emprego Do Sindicato Patronal", "Codigo do Vinculo Empregaticio da RAIS" )
        #define STR0108 If( cPaisLoc $ "ANG|PTG", "Descricao Do Vinculo De Emprego Do Sindicato Patronal", "Descricao do Vinculo Empregaticio da RAIS" )
        #define STR0109 If( cPaisLoc $ "ANG|PTG", "Codigo De Instrucao Do Sindicato Patronal", "Codigo de Instrucao da RAIS" )
        #define STR0110 If( cPaisLoc $ "ANG|PTG", "Descricao Do Codigo De Instrucao Do Sindicato Patronal", "Descricao do Codigo de Instrucao da RAIS" )
        #define STR0111 If( cPaisLoc $ "ANG|PTG", "Codigo De Rescisao Do Sindicato Patronal", "Codigo de Rescisao da RAIS" )
        #define STR0112 If( cPaisLoc $ "ANG|PTG", "Numero Do Distintivo", "Numero do Cracha" )
        #define STR0113 If( cPaisLoc $ "ANG|PTG", "Codigo Das Regras De Apontamentos", "Codigo da Regra de Apontamento" )
        #define STR0114 If( cPaisLoc $ "ANG|PTG", "Fotografia Do Funcionario", "Foto do Funcionario" )
        #define STR0115 If( cPaisLoc $ "ANG|PTG", "Numero De Registo", "Numero de Registro" )
        #define STR0116 If( cPaisLoc $ "ANG|PTG", "Numero Da Ficha", "Numero da Ficha" )
        #define STR0117 If( cPaisLoc $ "ANG|PTG", "Codigo Do Tipo De Contrato De Trabalho", "Codigo do Tipo de Contrato de Trabalho" )
        #define STR0118 If( cPaisLoc $ "ANG|PTG", "Descricao Do Tipo De Contrato De Trabalho", "Descricao do Tipo de Contrato de Trabalho" )
        #define STR0119 If( cPaisLoc $ "ANG|PTG", "Apelido Do Funcionario", "Apelido do Funcionario" )
        #define STR0120 If( cPaisLoc $ "ANG|PTG", "E-mail Do Funcionario", "E-mail do Funcionario" )
        #define STR0121 If( cPaisLoc $ "ANG|PTG", "Texto 01 Para Digitacao Livre", "Texto 01 para Livre Digitacao" )
        #define STR0122 If( cPaisLoc $ "ANG|PTG", "Texto 02 Para Digitacao Livre", "Texto 02 para Livre Digitacao" )
        #define STR0123 If( cPaisLoc $ "ANG|PTG", "Texto 03 Para Digitacao Livre", "Texto 03 para Livre Digitacao" )
        #define STR0124 If( cPaisLoc $ "ANG|PTG", "Texto 04 Para Digitacao Livre", "Texto 04 para Livre Digitacao" )
        #define STR0125 If( cPaisLoc $ "ANG|PTG", "Ordenado Por Extenso", "Extenso do Salario" )
        #define STR0126 If( cPaisLoc $ "ANG|PTG", "Data Base Do Sistema", "Data Base do Sistema" )
        #define STR0127 If( cPaisLoc $ "ANG|PTG", "Dia Da Data Base Do Sistema", "Dia da Data Base do Sistema" )
        #define STR0128 If( cPaisLoc $ "ANG|PTG", "Mes Da Data Base Do Sistema", "Mes da Data Base do Sistema" )
        #define STR0129 If( cPaisLoc $ "ANG|PTG", "Ano Da Data Base Do Sistema", "Ano da Data Base do Sistema" )
        #define STR0130 If( cPaisLoc $ "ANG|PTG", "Nome Da Empresa", "Nome da Empresa" )
        #define STR0131 If( cPaisLoc $ "ANG|PTG", "Morada Da Empresa", "Endereco da Empresa" )
        #define STR0132 If( cPaisLoc $ "ANG|PTG", "Municipio Da Empresa", "Municipio da Empresa" )
        #define STR0133 If( cPaisLoc $ "ANG|PTG", "Numero Do Cep Da Empresa", "Numero do CEP da Empresa" )
        #define STR0134 If( cPaisLoc $ "ANG|PTG", "CGC Da Empresa", "CGC da Empresa" )
        #define STR0135 If( cPaisLoc $ "ANG|PTG", "Numero Da Inscricao Estadual Da Empresa", "Numero da Inscricao Estadual da Empresa" )
        #define STR0136 If( cPaisLoc $ "ANG|PTG", "Telefone Da Empresa/fax", "Telefone da Empresa/Fax" )
        #define STR0137 If( cPaisLoc $ "ANG|PTG", "Bairro Da Empresa", "Bairro da Empresa" )
        #define STR0138 If( cPaisLoc $ "ANG|PTG", "Descricao Do Tipo De Rescisao Do Sindicato Patronal", "Descricao do Tipo de Rescisao da RAIS" )
        #define STR0139 If( cPaisLoc $ "ANG|PTG", "Dia Da Data De Demissao", "Dia da Data de Demissao" )
        #define STR0140 If( cPaisLoc $ "ANG|PTG", "Mes Da Data De Demissao", "Mes da Data de Demissao" )
        #define STR0141 If( cPaisLoc $ "ANG|PTG", "Ano Da Data De Demissao", "Ano da Data de Demissao" )
        #define STR0142 If( cPaisLoc $ "ANG|PTG", "Variavel", "Variavel" )
        #define STR0143 If( cPaisLoc $ "ANG|PTG", "Descricao Da Variavel", "Descricao da Variavel" )
        #define STR0144 If( cPaisLoc $ "ANG|PTG", "Relatorio Das Variaveis Gpe_Writer.", "Relatorio Variaveis GPE_Writer." )
        #define STR0145 If( cPaisLoc $ "ANG|PTG", "Sera impresso de acordo com os parametro s solicitados pelo", "Sera impresso de acordo com os parametros solicitados pelo" )
        #define STR0146 If( cPaisLoc $ "ANG|PTG", "Utilizador.", "usuario." )
        #define STR0147 If( cPaisLoc $ "ANG|PTG", "Codigo de barras", "Zebrado" )
        #define STR0148 If( cPaisLoc $ "ANG|PTG", "Administracao", "Administracäo" )
        #define STR0149 If( cPaisLoc $ "ANG|PTG", "Variaveis                      Descricao", "Variaveis                      Descricao" )
        #define STR0150 If( cPaisLoc $ "ANG|PTG", "Nome Do Dependente", "Nome do Dependente" )
        #define STR0151 If( cPaisLoc $ "ANG|PTG", "Data De Nascimento Do Dependente De Subsidio Familia", "Data de Nascimento do Dependente De Salario Familia" )
        #define STR0152 If( cPaisLoc $ "ANG|PTG", "Orgao Emissor Do Doc.identidade", "Orgao Emissor Doc.Identidade" )
        #define STR0153 If( cPaisLoc $ "ANG|PTG", "Relacao de dependencia ", "Relacao de Dependencia " )
        #define STR0154 If( cPaisLoc $ "ANG|PTG", "Dependente do imposto de renda ", "Dependente de Imposto de Renda " )
        #define STR0155 If( cPaisLoc $ "ANG|PTG", "Extenso do mes de admissao ", "Extenso do mes de admissao " )
        #define STR0156 If( cPaisLoc $ "ANG|PTG", "Nome do apoderado", "Nome do apoderado " )
        #define STR0157 If( cPaisLoc $ "ANG|PTG", "Actividade da empresa ", "Atividade da empresa " )
        #define STR0158 If( cPaisLoc $ "ANG|PTG", "Numero Do Livro Em Que Foi Registado", "Numero do Livro em que foi Registrado" )
        #define STR0159 If( cPaisLoc $ "ANG|PTG", "Numero Da Folha Do Livro Em Que Foi Registado", "Numero da Folha do Livro em que foi Registrado" )
        #define STR0160 If( cPaisLoc $ "ANG|PTG", "Data Da Entrega Dos Documentos", "Data da Entrega dos Documentos" )
        #define STR0161 If( cPaisLoc $ "ANG|PTG", "Data Da Liquidacao Dos Documentos", "Data da Baixa dos Documentos" )
        #define STR0162 If( cPaisLoc $ "ANG|PTG", "A Seleccionar Registos.....", "Selecionando Registros....." )
        #define STR0163 If( cPaisLoc $ "ANG|PTG", "Data De Nascimento Do Dependente De IRS", "Data de Nascimento do Dependente De Imposto de Renda" )
        #define STR0164 If( cPaisLoc $ "ANG|PTG", "Local De Nascimento", "Local de Nascimento" )
        #define STR0165 If( cPaisLoc $ "ANG|PTG", "Numero Do Registo De Nascimento", "Numero do Registro de Nascimento" )
        #define STR0166 If( cPaisLoc $ "ANG|PTG", "Concelho De Nascimento", "Municipio de Nascimento" )
        #define STR0167 If( cPaisLoc $ "ANG|PTG", "A integracao Writer funciona somente com windows!!!", "Integracao Writer funciona somente com Windows !!!" )
        #define STR0168 "Atencao !"
        #define STR0169 "Primeiro Nome"
        #define STR0170 "Segundo Nome"
        #define STR0171 "Primeiro Sobrenome"
        #define STR0172 "Segundo Sobrenome"
        #define STR0173 If( cPaisLoc $ "ANG|PTG", "Codigo Do Processo", "Codigo do Processo" )
        #define STR0174 If( cPaisLoc $ "ANG|PTG", "Codigo  Do Local De Pagamento", "Codigo do Local de Pagamento" )
        #define STR0175 If( cPaisLoc $ "ANG|PTG", "Tipo De Remuneracao Imss", "Tipo de Salario IMSS" )
        #define STR0176 If( cPaisLoc $ "ANG|PTG", "Tipo De Empregado Imss", "Tipo de Empregado IMSS" )
        #define STR0177 If( cPaisLoc $ "ANG|PTG", "Tipo De Dia Imss", "Tipo de Jornada IMSS" )
        #define STR0178 If( cPaisLoc $ "ANG|PTG", "Data De Readmissao", "Data de Readmissao" )
        #define STR0179 If( cPaisLoc $ "ANG|PTG", "Data De Liquidacao    Imss", "Data de Baixa IMSS" )
        #define STR0180 If( cPaisLoc $ "ANG|PTG", "Codigo  Do Registo Patronal", "Codigo do Registro Patronal" )
        #define STR0181 If( cPaisLoc $ "ANG|PTG", "Codigo  Do Departamento", "Codigo do Departamento" )
        #define STR0182 If( cPaisLoc $ "ANG|PTG", "Codigo Do Posto", "Codigo do Posto" )
        #define STR0183 If( cPaisLoc $ "ANG|PTG", "Curp", "CURP" )
        #define STR0184 If( cPaisLoc $ "ANG|PTG", "Tipo De Infonavit", "Tipo de Infonavit" )
        #define STR0185 If( cPaisLoc $ "ANG|PTG", "Valor Do Infonavit", "Valor do Infonavit" )
        #define STR0186 If( cPaisLoc $ "ANG|PTG", "Nro. De Credito Infonavit", "Nro. de Credito Infonavit" )
        #define STR0187 If( cPaisLoc $ "ANG|PTG", "A endereco completo do local onde esta o arquivo do Writer excedeu o limite de 75 caracteres!", "O endereco completo do local onde esta o arquivo do Writer excedeu o limite de 75 caracteres!" )
        #define STR0188 If( cPaisLoc $ "ANG|PTG", "Dia Inicio Per.Aquis.Ferias", "Dia Inicio Per.Aquis.Ferias" )
        #define STR0189 If( cPaisLoc $ "ANG|PTG", "Mes Inicio Per.Aquis.Ferias", "Mes Inicio Per.Aquis.Ferias" )
        #define STR0190 If( cPaisLoc $ "ANG|PTG", "Ano Inicio Per.Aquis.Ferias", "Ano Inicio Per.Aquis.Ferias" )
        #define STR0191 If( cPaisLoc $ "ANG|PTG", "Dia Fim Per.Aquis.Ferias", "Dia Fim Per.Aquis.Ferias" )
        #define STR0192 If( cPaisLoc $ "ANG|PTG", "Mes Fim Per.Aquis.Ferias", "Mes Fim Per.Aquis.Ferias" )
        #define STR0193 If( cPaisLoc $ "ANG|PTG", "Ano Fim Per.Aquis.Ferias", "Ano Fim Per.Aquis.Ferias" )
        #define STR0194 "Descricao do Estado Civil"
        #define STR0195 "Nr. Bilhete Identidade"
        #define STR0196 "Data de Emissao do Bilhete Identidade"
        #define STR0197 "Descricao da primeira tarefa encontrada"
        #define STR0198 "Aulas por semana da primeira tarefa"
        #define STR0199 "Quantidade da primeira tarefa"
        #define STR0200 "Valor unitario da primeira tarefa"
        #define STR0201 "Valor total da primeira tarefa"
        #define STR0202 "Descricao da segunda tarefa"
        #define STR0203 "Aulas por semana da segunda tarefa"
        #define STR0204 "Quantidade da segunda tarefa"
        #define STR0205 "Valor unitario da segunda tarefa"
        #define STR0206 "Valor total da segunda tarefa"
        #define STR0207 "Numero Patronal para o CCSS"
        #define STR0208 "Numero de Apolice para MTSS"
        #define STR0209 "Numero da Filial do CCSS"
        #define STR0210 "Codigo de Ocupacao MTSS"
        #define STR0211 "Codigo de Ocupacao CCSS"
        #define STR0212 "Codigo de Ocupacao INS"
        #define STR0213 "Descricao do Codigo de Ocupacao MTSS"
        #define STR0214 "Descricao do Codigo de Ocupacao CCSS"
        #define STR0215 "Descricao do Codigo de Ocupacao INS"
        #define STR0216 "Descricao da Localidade de Pagamento"
        #define STR0217 "Turno de Trabalho"
        #define STR0218 "Horas por Dia"
        #define STR0219 "Distrito onde vive o trabalhador"
        #define STR0220 "Descricao do Distrito"
        #define STR0221 "Cantao onde vive o trabalhador"
        #define STR0222 "Descricao do Cantao onde vive o trabalhador"
        #define STR0223 "Estado onde vive o trabalhador"
        #define STR0225 "Tipo de Demissao de Acordo com a Empresa"
        #define STR0226 "Tipo numero de identificacao"
        #define STR0227 "Numero do Seguro Social"
        #define STR0228 "Descricao Jornada"
        #define STR0229 "Data de Modificacao de Salario"
        #define STR0230 "Estrangeiro vivendo no pais (1=Sim, 2=Nao)"
        #define STR0231 "Tipo de Moeda para o Salario em contrato"
        #define STR0232 "Associacao Solidarista"
        #define STR0233 "Descricao Associacao Solidarista"
        #define STR0234 "Classe Seguro"
        #define STR0235 "Numero Assegurado"
        #define STR0236 "Tipo de Gross up de Salario"
        #define STR0237 "Salario Anterior"
        #define STR0238 "Atencao"
        #define STR0239 "Execute a opcao do compatibilizador referente a 'Disponibilizacao dos campos RA_HABILIT e RA_COMPLEM para o Equador'. Para maiores informacoes, verifique respectivo Boletim Tecnico."
        #define STR0240 "OK"
        #define STR0241 "UF do Orgao Emissor Do Doc.identidade"
        #define STR0242 "Exportar Variaveis"
    #define STR0243 "Emissao CTPS"
    #define STR0244 "Raca\Cor"
    #define STR0245 "Data da Segunda Experiencia"
    #define STR0246 "Dia da Segunda Experiencia"
    #define STR0247 "Mes da Segunda Experiencia"
    #define STR0248 "Ano da Segunda Experiencia"
    #define STR0249 "Dias da Segunda Experiencia"
    #define STR0250 "Marca 'x' se Nacionalidade Brasileira"
    #define STR0251 "Marca 'x' se Nacionalidade Extrangeira"
    #define STR0252 "Marca 'x' se Nacionalidade Brasileira Naturalizada"
    #define STR0253 "Marca 'x' se Nacionalidade Brasileiro Nascido no Exterior"
    #define STR0254 "Estado civil de acordo com o NIS/PIS"
    #define STR0255 "Nome do Pai,informa IGNORADO caso esteja em branco"
    #define STR0256 "Nome da Mae,informa IGNORADO caso esteja em branco"
    #define STR0257 "Complemento do RG"
    #define STR0258 "Tipo de Certidao Civil"
    #define STR0259 "Data de Emissao da Certidao Civil"
    #define STR0260 "Termo/Matricula da Certidao Civil"
    #define STR0261 "Livro da Certidao Civil"
    #define STR0262 "Folha da Certidao Civil"
    #define STR0263 "Cartorio da Certidao Civil"
    #define STR0264 "UF da Certidao Civil"
    #define STR0265 "Municipio da Certidao Civil"
    #define STR0266 "Numero do Passaporte"
    #define STR0267 "Orgao Emissor do Passaporte"
    #define STR0268 "UF do Passaporte"
    #define STR0269 "Data Emissao Passaporte"
    #define STR0270 "Data Validade Passaporte"
    #define STR0271 "Pais de Emissao Passaporte"
    #define STR0272 "Numero de Naturalizacao"
    #define STR0273 "Data de Naturalizacao"
    #define STR0274 "Numero do RIC"
    #define STR0275 "Orgao Emissor do RIC"
    #define STR0276 "UF do RIC"
    #define STR0277 "Municipio do RIC"
    #define STR0278 "Data de Expedicao do RIC"
    #define STR0279 "Marca 'x' se Endereco for Comercial"
    #define STR0280 "Marca 'x' se Endereco for Residencial"
    #define STR0281 "Numero do Endereco"
    #define STR0282 "Caixa Postal"
    #define STR0283 "CEP da Caixa Postal"
    #define STR0284 "DDD do Telefone"
    #define STR0285 "DDD do Celular"
    #define STR0286 "Numero do Celular"
    #define STR0287 "Marca 'x' se Empresa por CNPJ"
    #define STR0288 "Marca 'x' se Empresa por CEI"
    #define STR0289 "Data de Expedicao do RIC"
    #define STR0290 "Secao Eleitoral"
    #define STR0291 "Grau de Instrucao conforme NIS/PIS"
    #define STR0292 "Pais de Origem para o DCN/DMN"
    #define STR0295 "Descricao do Grau de Instrucao"
    #define STR0296 "Descricao do Grau de Instrucao"
    #define STR0297 "Descricao do Grau de Instrucao"
    #define STR0298 "Descricao do Grau de Instrucao"
    #define STR0299 "Descricao do Grau de Instrucao"
    #define STR0300 "Descricao do Grau de Instrucao"
    #define STR0301 "Descricao do Grau de Instrucao"
    #define STR0302 "Descricao do Grau de Instrucao"
    #define STR0303 "Descricao do Grau de Instrucao"
    #define STR0304 "Descricao do Grau de Instrucao"
    #define STR0305 "Descricao do Grau de Instrucao"
    #define STR0306 "Descricao do Grau de Instrucao"
    #define STR0307 "Descricao do Grau de Instrucao"
    #define STR0308 "Estado de Nascimento NIS/PIS"
    #define STR0309 "Municipio de Nascimento NIS/PIS"
    #define STR0310 "Marca 'x' para tipo de DMN - Alteracao"
    #define STR0311 "Marca 'x' para tipo de DMN - Cadastro Retroativo"
    #define STR0312 "Marca 'x' para tipo de DMN - Cancelamento"
    #define STR0313 "Marca 'x' para tipo de DMN - Reativacao"
    #define STR0314 "Marca 'x' para tipo de DMN - Retroacao Cadastral"
    #define STR0315 "Marca 'x' se sexo for Masculino"
    #define STR0316 "Marca 'x' se sexo for Feminino"
    #define STR0317 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0318 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0319 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0320 "Adequacao da descricao do certificado civil conforme o leiaute do DCN/DMN - PIS"
    #define STR0321 "Informe o Tipo de Alteracao do NIS-PIS"
    #define STR0322 "Nenhum"
    #define STR0323 "Alteracao"
    #define STR0324 "Cadastro Retroativo"
    #define STR0325 "Cancelamento"
    #define STR0326 "Reativacao"
    #define STR0327 "Retroacao Cadastral"
    #define STR0328 "Endereco da Localidade de Pagamento"
    #define STR0329 "Bairro da Localidade de Pagamento"
    #define STR0330 "Cidade da Localidade de Pagamento"
    #define STR0331 "Estado da Localidade de Pagamento"
    #define STR0332 "Municipio da Localidade de Pagamento"
    #define STR0333 "CEP da Localidade de Pagamento"
    #define STR0334 "Requisitos da Funcao"
    #define STR0335 "Idade"    
    #define STR0336 "Codigo da Serventia"
    #define STR0337 "Codigo do Acervo"
    #define STR0338 "Registro Civil"
    #define STR0339 "Tipo do Livro Reg."
    #define STR0340 ""
    #define STR0341 ""
    #define STR0342 ""
    #define STR0343 ""
    #define STR0344 ""
    #define STR0345 ""
    #define STR0346 ""
    #define STR0347 ""
    #define STR0348 ""
    #define STR0349 ""
    #define STR0350 ""
    #define STR0351 ""
    #define STR0352 ""
    #define STR0353 ""
    #define STR0354 ""
    #define STR0355 ""
    #define STR0356 ""
    #define STR0357 ""
    #define STR0358 ""
    #define STR0359 ""
    #define STR0360 ""
    #define STR0361 ""
    #define STR0362 ""
    #define STR0363 ""
    #define STR0364 ""
    #define STR0365 ""
    #define STR0366 ""
    #define STR0367 ""
    #define STR0368 ""
    #define STR0369 ""
    #define STR0370 ""
    #define STR0371 ""
    #define STR0372 ""
    #define STR0373 ""
    #define STR0374 ""
    #define STR0375 ""
    #define STR0376 ""
    #define STR0377 ""
    #define STR0378 ""
    #define STR0379 ""
    #define STR0380 ""
    #define STR0381 ""
    #define STR0382 ""
    #define STR0383 ""
    #define STR0384 ""
    #define STR0385 ""
    #define STR0386 ""
    #define STR0387 ""
    #define STR0388 ""
    #define STR0389 ""
    #define STR0390 "Descricao da atividade da funcao"
    #endif
#endif
