SELECT MAX(x.DOCSEC) 
  FROM (
            SELECT MAX(D1_NUMSEQ) DOCSEC FROM SD1010
            UNION
            SELECT MAX(D2_NUMSEQ) DOCSEC FROM SD2010
            UNION
            SELECT MAX(D3_NUMSEQ) DOCSEC FROM SD3010
  ) x