#DEFINE FILTER          1
#DEFINE FILTER_ADVPL    2
#DEFINE FILTER_SQL      3
#DEFINE FILTER_PARSER   4
#DEFINE FILTER_NOCHECK  5
#DEFINE FILTER_SELECTED 6
#DEFINE FILTER_ASK      7
#DEFINE FILTER_ALIAS    8
#DEFINE FILTER_ID       9
#DEFINE FILTER_FUNCT   10

#DEFINE FILTER_ARRAY_SIZE 10

#DEFINE FILTER_PARSER_VALUE 1
#DEFINE FILTER_PARSER_TYPE  2

