
#DEFINE PARAM_ID			 1
#DEFINE PARAM_IDCONJ		 2
#DEFINE PARAM_NOME			 3
#DEFINE PARAM_CAPTION		 4
#DEFINE PARAM_HINT			 5
#DEFINE PARAM_ORDEM			 6
#DEFINE PARAM_TIPOCTRLGR	 7
#DEFINE PARAM_IDPARAMGR		 8
#DEFINE PARAM_PROPERTNAM	 9
#DEFINE PARAM_ONINIT		10
#DEFINE PARAM_ONVALID		11
#DEFINE PARAM_COLUMNNAME	12
#DEFINE PARAM_TIPO			13


